// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczVUW02Ef4zgLYGd6BvhU84g2NXssGhY',
    appId: '1:69896345577:web:734e115e7457f03d6f5d78',
    messagingSenderId: '69896345577',
    projectId: 'notes-app-101025',
    authDomain: 'notes-app-101025.firebaseapp.com',
    storageBucket: 'notes-app-101025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAczVUW02Ef4zgLYGd6BvhU84g2NXssGhY',
    appId: '1:69896345577:web:e9e48b019db107046f5d78',
    messagingSenderId: '69896345577',
    projectId: 'notes-app-101025',
    authDomain: 'notes-app-101025.firebaseapp.com',
    storageBucket: 'notes-app-101025.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGtl4rsY8WpDYcNVYwksBpYW6h4bX-1M',
    appId: '1:69896345577:ios:04b457e5ecb4726b6f5d78',
    messagingSenderId: '69896345577',
    projectId: 'notes-app-101025',
    storageBucket: 'notes-app-101025.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGtl4rsY8WpDYcNVYwksBpYW6h4bX-1M',
    appId: '1:69896345577:ios:04b457e5ecb4726b6f5d78',
    messagingSenderId: '69896345577',
    projectId: 'notes-app-101025',
    storageBucket: 'notes-app-101025.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp390W-wzQH08ZoaAA4IrpuMIgFMfmM5Y',
    appId: '1:69896345577:android:ac15c66e386bdc2a6f5d78',
    messagingSenderId: '69896345577',
    projectId: 'notes-app-101025',
    storageBucket: 'notes-app-101025.firebasestorage.app',
  );

}